### PR TITLE
Update strings Portuguese (Brazil)

### PR DESCRIPTION
**Pull request by Aybar1881**
Translated Success, "BATALHA REAL" has been changed to "BATTLE ROYALE" cuz its special name. Translated Mod names.

### CODE REVIEW

**Comment by Jeii20** [comment]
PR closed. Too many wrong changes.

**Comment by Aybar1881** [comment]
> PR closed. Too many wrong changes. Plus: you actually edited Portugal file. "Success" translation is correct, but the other rest are invalid changes

So can i just Change for Succes? And open New PR for success?

**Comment by Jeii20** [comment]
You can look for other texts. These you tried to change must remain the same, especially "MEGA SPLIT 64X" and "CRAZY SPLIT 32X", because of the typeface that may not work well.

**Comment by Aybar1881** [comment]
> You can look for other texts. These you tried to change must remain the same, especially "MEGA SPLIT 64X" and "CRAZY SPLIT 32X", because of the typeface that may not work well.

Got it thanks😊

**Pull request closed without merging**
