### PR TITLE
Update strings.xml

### PR DESCRIPTION
**Pull request by LaFurraDiana**

### CODE REVIEW

**Comment by LaFurraDiana** [comment]
Identificación Nebulous:14282977

**Comment by LaFurraDiana** [comment]
Poland

**Review by Jeii20 — APPROVED** [review]

**Comment by Jeii20** [comment]
@AnkaKoxu please see if this is correct

**Comment by AnkaKoxu** [comment]
On the way! I'll let know by tomorrow at the latest.

**Comment by Jeii20** [comment]
No rushes ^^

**Comment by AnkaKoxu** [comment]
Screenshot_20240831_233249_Chrome

@egzoticxyz

**Comment by Jeii20** [comment]
Thank you.

PR closed. Invalid change.

**Pull request closed without merging**
