### PR TITLE
Update strings.xml

### PR DESCRIPTION
**Pull request by syd7om**
ID : 24051125

### CODE REVIEW

**Comment by Jeii20** [comment]
Please provide a reason for this change and why the previous text was wrong with evidences, as it says on **Tips**:

"Adding comments to your PR that explains why subtle changes were made can help. If you are revising something that is already translated, an explanation is required."

**Comment by syd7om** [comment]
I replied

**Comment by Jeii20** [comment]
PR closed. No reason provided for such change (mandatory).

**Comment by syd7om** [comment]
Hi

في خميس، 26 سبتمبر، 2024 في 4:56 م، كتب Jeii20 ***@***.***>:

**Pull request closed without merging**
