### PR TITLE
Admin commands list update and a translation fix for Spanish

### PR DESCRIPTION
**Pull request by Jeii20**

### CODE REVIEW

**Comment by Jeii20** [comment]
I made an accidental change at string BATTLE ROYALE, but it's fixed in the next file.

**Review by CritiKangel — APPROVED** [review]

**Comment by CritiKangel** [comment]
You deleted the command "!guests" in string number 1354, after "!hidden!

**Comment by Jeii20** [comment]
Yes, because the command doesn't exist anymore, I tested before I applied, and anyway they can't play without signing in! ^^

**Comment by Jeii20** [comment]
> You deleted the command "!guests" in string number 1354, after "!hidden!

Yes, because the command doesn't exist anymore, I tested before I applied, and anyway they can't play without signing in! ^^

**Comment by CritiKangel** [comment]
> > You deleted the command "!guests" in string number 1354, after "!hidden!
> 
> Yes, because the command doesn't exist anymore, I tested before I applied, and anyway they can't play without signing in! ^^

let's not delete anything from the original without the dev's permission

**Comment by Jeii20** [comment]
> > > You deleted the command "!guests" in string number 1354, after "!hidden!
> > 
> > Yes, because the command doesn't exist anymore, I tested before I applied, and anyway they can't play without signing in! ^^
> 
> let's not delete anything from the original without the dev's permission

Noted, sorry for my mistake and thank you for letting me aware. ^^

**Pull request merged**
