### PR TITLE
Turkısh TR Translation Improvements

### PR DESCRIPTION
**Pull request by akil35**
ID 14037166

### CODE REVIEW

**Comment by akil35** [comment]
14037166

**Review by akil35 — COMMENTED** [review]
14037166

**Comment by zeynpcna2** [comment]
These already exist in the tr file ?
can u check tr file

**Comment by akil35** [comment]
> ID 14037166

**Comment by akil35** [comment]
> ID 14037166

**Review by akil35 — COMMENTED** [review]
ID 14037166

**Pull request closed without merging**
