### PR TITLE
update Arabic language

### PR DESCRIPTION
**Pull request by m21n22**
lD: 29369269

### CODE REVIEW

**Comment by MaRs001V** [comment]
🙂🙂🙂🙂

**Comment by Jeii20** [comment]
PR closed. Invalid changes at lines **123** and **253** (changed original string name). Please never change these places, otherwise they may result in a conflict if applied.

**Review by AssaNebulous — COMMENTED** [review]
This PR contains inaccurate changes in several strings.

**Comment by m21n22** [comment]
😢

في الأربعاء، ٢٨ أغسطس ٢٠٢٤, ٢:٥٣ م MaRs001V ***@***.***> كتب:

**Pull request closed without merging**
