### PR TITLE
Improvement of Korean translation

### PR DESCRIPTION
**Pull request by Limsoohyeon**
Game ID 17187381

### CODE REVIEW

**Review by Jeii20 — APPROVED** [review]
Already approved the changes, can merge into main if possible.

**Comment by Limsoohyeon** [comment]
Can I get the title of translator?

**Comment by Limsoohyeon** [comment]
Can I get the title of translation?

**Comment by Majaaaa1** [comment]
@Limsoohyeon please be patient, everything needs to be checked and confirmed before the tag is granted.

**Pull request merged**
