### PR TITLE
Update strings.xml

### PR DESCRIPTION
**Pull request by JSI31**
lD 27054296

### CODE REVIEW

**Comment by Jeii20** [comment]
As it says on **Tips**:

"Adding comments to your PR that explains why subtle changes were made can help. If you are revising something that is already translated, an explanation is required."

Please always provide the reason for whose changes next times.

**Comment by JSI31** [comment]
I want the title of translator lD 27054296

**Comment by Jeii20** [comment]
PR closed. Invalid argument.

**Comment by JSI31** [comment]
***@***.***

في السبت، ٣١ أغسطس ٢٠٢٤, ٢:٠١ م Jeii20 ***@***.***> كتب:

**Comment by JSI31** [comment]
I just want to apply for the title lD 27054296

**Pull request closed without merging**
