### PR TITLE
Update strings.xml

### PR DESCRIPTION
**Pull request by iyads7**
ID:32087443

### CODE REVIEW

**Comment by Jeii20** [comment]
Please provide a reason for this change and why the previous text was wrong with proof, as it says on **Tips**:

"Adding comments to your PR that explains why subtle changes were made can help. If you are revising something that is already translated, an explanation is required."

**Comment by iyads7** [comment]
I want to get the title of translator in the game nebulos.io

‫في السبت، 28 سبتمبر 2024 في 12:15 ص تمت كتابة ما يلي بواسطة ‪Jeii20‬‏ <‪
***@***.***‬‏>:‬

**Comment by Jeii20** [comment]
PR closed. Invalid argument.

@iyads7 
Please consider the following topics for next time:

- Adding comments to your PR that explains why subtle changes were made can help. If you are revising something that is already translated, an explanation is **required**.
**MEANING: You need to always provide reason why you are changing the already translated text and explain with proof why the previous text was wrong.**
- Only edit files if you see something wrong with the translations. You must check in-game first if there's a typo, missing punctuation, term used on invalid context or any similar mistake, so you can look for the string line that belongs to that/those specific text(s) to be corrected for your language.
**MEANING: You should NOT make any change if you don't find inaccuracy with in-game translations. A full review of the specific language file you are about to change is also advisable.**
- Making small, random or inconsistent changes on the file just for the Translator tag is not worth it. It's mandatory that you have at least knowledge on the English language and make sure you have a good writing on your native language or **any** other language you are about to change. The game translation algorithm must always be taken very seriously.
**MEANING: Translator tag cannot be used for fun nor be used to distribute to anyone everywhere. This is a big and frank commitment with the team for _translating_ the game. You should NOT run for the Translator tag because it seems "beautiful" with the cyan ID colour or to accumulate all the tags in the game (those are the most common reasons why the whole community wants such tag nowadays). This service needs to be taken seriously.**

I hope you can understand it. ^^

**Comment by iyads7** [comment]
Thank you so much for the great news!

‫في السبت، 28 سبتمبر 2024 في 1:49 ص تمت كتابة ما يلي بواسطة ‪Jeii20‬‏ <‪
***@***.***‬‏>:‬

**Comment by iyads7** [comment]
But you did not give me the title of translator

‫في السبت، 28 سبتمبر 2024 في 10:18 ص تمت كتابة ما يلي بواسطة ‪THE END S7‬‏
***@***.***‬‏>:‬

**Comment by Jeii20** [comment]
@iyads7 
I am not giving it, just the developer. And you didn't make valid changes to be elligible. And please, as I said, never make changes **just** for the Translator tag.

**Comment by iyads7** [comment]
Ok, I understand.

‫في السبت، 28 سبتمبر 2024 في 11:55 ص تمت كتابة ما يلي بواسطة ‪Jeii20‬‏ <‪
***@***.***‬‏>:‬

**Pull request closed without merging**
