### PR TITLE
Update strings.xml Ro(Romain)

### PR DESCRIPTION
**Pull request by AlExX2457**
Update Strings.xml Ro
They're wrong every time, so many times I keep saying it's spelled wrong !
My ID is: 20713867

The punctuation marks are wrong, that's not how we are used in Romanian, totally wrong (most of them)

### CODE REVIEW

**Review by AssaNebulous — COMMENTED** [review]
hello, in some changes you removed the punctuation from the end, I think these changes are incorrect.

I didn't find anything that confirms your request in saying that Romanian does not use punctuation at the end of sentences.

**Comment by AnkaKoxu** [comment]
Could you explain why full stops are not used in the majority, give any examples?

why is there a dot in some sentences? e.g. here?

**Comment by AlExX2457** [comment]
They left it like that, most of them are without punctuation marks, only with a comma, when we finish a word we don't put (.)
Some I forgot to remove, that's why it's like that, I missed many
Sometimes we use punctuation marks at the end of sentences

**Comment by Jeii20** [comment]
> Hello There!
> They left it like that, most of them are without punctuation marks, only with a comma, when we finish a word we don't put (.) just sometimes some stories have long sentences
> 
> Some I forgot to remove, that's why it's like that, I missed many

In-game it's needed that they keep like it were before @AlExX2457

**Comment by AlExX2457** [comment]
I understand but this seems wrong to me 
@Jeii20

**Comment by Jeii20** [comment]
First please fix the punctuations you removed

**Comment by AlExX2457** [comment]
Ok, i will fix it, but you promis you will accept my translator into romain?

**Comment by AlExX2457** [comment]
@Jeii20 Please check if it's ok now! I want to be a Romanian translator one day! Nothing else! Please, how long do I have to wait?

**Comment by AnkaKoxu** [comment]
It has become such a chaos with these punctuations that it is not clear what is correct. Match everything with english' strings. Because once you give those dots and once you don't, and once change them. It is no longer clear whether this is even a good thing, as you have only 35 improved latest out of over 1000+.

**Comment by AlExX2457** [comment]
I deleted the tab with the power points as Jai told me, the rest is fine, I translated what was not translated

**Comment by AssaNebulous** [comment]
You deleted all the code...

**Comment by AlExX2457** [comment]
No, i didn't,go look up, I only deleted what he said

**Comment by Jeii20** [comment]
PR closed. Commit file has been deleted (probably by mistake).

**Pull request closed without merging**
