### PR TITLE
Update strings.xml

### PR DESCRIPTION
**Pull request by JSI31**
lD: 27054296 
The incorrect words were changed and corrected 
Arabic

### CODE REVIEW

**Comment by JSI31** [comment]
It's ok Greg @grog444

**Comment by Jeii20** [comment]
@JSI31 please stop mentioning developer here and be patient.

**Comment by Majaaaa1** [comment]
After several warnings and many explanations, he continues to open the tickets and force what he wants.
 @JSI31 I ask you to pay attention to what is being said to you, to follow the instructions and to be patient. why are you looking for a tag if you don't understand English, how do you mean to translate, when you don't understand what is needed.

**Comment by Jeii20** [comment]
PR closed. We found invalid changes in all the lines you changed.

**Comment by JSI31** [comment]
Good

**Pull request closed without merging**
