### PR TITLE
Update strings.xml

### PR DESCRIPTION
**Pull request by Heren-o**
ID: 29861062

### CODE REVIEW

**Comment by Jeii20** [comment]
Please provide a reason for these changes and explain with proof why the previous texts were incorrect, as it says on **Tips** topic:

"Adding comments to your PR that explains why subtle changes were made can help. If you are revising something that is already translated, an explanation is **required**."

**Comment by Heren-o** [comment]
1- I saw that there are some small mistakes, so I modified them


2- I want the title of translator


في أربعاء، ٢ أكتوبر، ٢٠٢٤ في ٢:١١ م، كتب Jeii20 ***@***.***>:

**Comment by Jeii20** [comment]
**Replying to your 1.** Yes, but you still didn't provide a reason why they are wrong with enough evidence.
**Replying to your 2.** Making small, random or inconsistent changes on the file just for the Translator tag is not worth it. It's mandatory that you have at least knowledge on the English language and make sure you have a good writing on your native language or **any** other language you are about to change. The game translation algorithm must always be taken very seriously.
**MEANING: Translator tag cannot be used for fun nor be used to distribute to anyone everywhere. This is a big and frank commitment with the team for _translating_ the game. You should NOT run for the Translator tag because it seems "beautiful" with the cyan ID colour, because you saw someone with the tag on in-game chat or mail, or to accumulate all the tags in the game (those are the most common reasons why the whole community wants such tag nowadays). This service needs to be taken seriously.**

**Comment by TurkiAlanazi1** [comment]
It should not be changed.
It is my language and I see many mistakes

**Comment by Heren-o** [comment]
انها لغتي ايضًا ولم ارى بها اخطاء الترجمه صحيحه

في أربعاء، ٩ أكتوبر، ٢٠٢٤ في ٦:٤٧ م، كتب Turki Alanazi <
***@***.***>:

**Comment by Heren-o** [comment]
I didn't think so deeply, I apologise,
thanks for reply


في أربعاء، ٢ أكتوبر، ٢٠٢٤ في ٢:٥٥ م، كتب Jeii20 ***@***.***>:

**Pull request closed without merging**
