### PR TITLE
Update strings.xml Ro

### PR DESCRIPTION
**Pull request by AlExX2457**
ID: 20713867
I found spelling mistakes
 (English-Romain)

### CODE REVIEW

**Comment by AnkaKoxu** [comment]
Screenshot_20240901_071450_Chrome

Variable may not undergo any formatting or modification. It should remain as it is: %d.

**Comment by AnkaKoxu** [comment]
1) I'm thinking that it will be too long to match in the UI.
2) The length ratio between the ro-ang string is about 3:1

Screenshot_20240901_071922_Chrome

**Comment by Jeii20** [comment]
PR closed. Invalid changes. Please never change or remove %d, %s or \n, as @AnkaKoxu mentioned.

**Comment by AlExX2457** [comment]
Okay, thank you!

**Comment by JSI31** [comment]
You don't have to change the words

**Pull request closed without merging**
