### PR TITLE
Update Turkish Transloter

### PR DESCRIPTION
**Pull request by Savas400-star**
2 more wrong word was found, making a total of 8 words. I request a "Translator".
ID:22214479

### CODE REVIEW

**Comment by zeynpcna2** [comment]
Why u did change 5x= Quin is correct
Which  One=Hangisi?

**Comment by Savas400-star** [comment]
"Quin"  It doesn't mean 5x, it means Five.

**Comment by Savas400-star** [comment]
It doesn't mean 5x, it means Five lik.

**Comment by Savas400-star** [comment]
That sentence needs to be changed, my second statement is also correct.

**Comment by Savas400-star** [comment]
Another wrong word was found.

23 Ağu 2024 Cum ÖÖ 8:50 tarihinde zeynp ***@***.***> şunu
yazdı:

**Comment by zeynpcna2** [comment]
Battle kelimesini önceki çeviride düzelt işsin onayladım ama oyunda 5x Quin  5 katı anlamnda kullanıldı

**Pull request closed without merging**
