### PR TITLE
Update and rename strings.xml to strings.xml

### PR DESCRIPTION
**Pull request by Hade-23**
Id:27834320

### CODE REVIEW

**Review by Jeii20 — CHANGES_REQUESTED** [review]
Please remove the spacebar in the middle of text

**Comment by Hade-23** [comment]
How can I do this?

**Comment by TurkiAlanazi1** [comment]
> How can I do this?

Open another

**Comment by Jeii20** [comment]
> Open another

He doesn't really need create another pull request. He can simply access the file again through the same PR, and after done, he can push another commit here

**Comment by Hade-23** [comment]
I have opened a new request for you to review.

في الاثنين، ٢٦ أغسطس ٢٠٢٤, ٣:٥٩ م Jeii20 ***@***.***> كتب:

**Pull request closed without merging**
