### PR TITLE
Update strings.xml valores-b+es+r419 idioma latinoamericano

### PR DESCRIPTION
**Pull request by leejose20**
Word correction :) thanks

### CODE REVIEW

**Comment by Jeiii20** [comment]
PR closed. @leejose20 please stop inserting punctuation where is not needed next time.

**Comment by leejose20** [comment]
Pero @Jeiii20 yo cuando lo envié decía q estaba bien, en todo caso pido perdón.
Me olvidé colocar mi id de nebulous. 
ID: 20146204

**Comment by Jeiii20** [comment]
Yes but you based off completely by the tutorial video, especially on inserting a dot. You should insert punctuations only in really needed cases and check if there's something wrong with the texts in your mother language, and avoid making random changes just to get the translator tag. You can get it, but at fair way.
@leejose20

**Comment by leejose20** [comment]
Ok, entiendo, pero si ise cambios en algunas palabras también, no solo fue puntos.
@Jeiii20 entonces tengo q volver hacerlo o que solución hay? 😔

**Comment by Jeiii20** [comment]
Yes, because you messed up too much with random changes and cases like that cannot be elligible to have a tag and will result in a closement of your pull request.

**Comment by leejose20** [comment]
Entiendo, puedo editarlo o tengo q si o si hacer uno nuevo?

**Comment by Jeiii20** [comment]
Submit a new, please

**Comment by leejose20** [comment]
Entendido

**Pull request closed without merging**
