### PR TITLE
Update Strings Romain

### PR DESCRIPTION
**Pull request by AlExX2457**
Update Strings.xml To Romain Ro

### CODE REVIEW

**Review by AssaNebulous — APPROVED** [review]
Good Job!

**Comment by AlExX2457** [comment]
Thank you Sir! 😌

**Comment by Jeii20** [comment]
PR closed. Invalid changes in some lines. Please never remove or change the `%s`, `#d` or `\n`, they need to remain the same as the English file: `res/values`.

**Comment by AlExX2457** [comment]
Okay, thank you

**Pull request closed without merging**
