### PR TITLE
valores-pt-rBR

### PR DESCRIPTION
**Pull request by Banned44nebu**
Tradução dos comandos do nebulous 
Remoção do "guests " porque não tem mais  no jogo.

### CODE REVIEW

**Comment by Banned44nebu** [comment]
ID: 23262964

**Comment by Jeii20** [comment]
PR closed. Please do not remove the command descriptions, they are provided for those who don't understand english.

**Comment by Jeii20** [comment]
Could you please re-send it again? I closed it thinking it was values-pt-rBR and because I thought you removed them.

**Comment by Banned44nebu** [comment]
Okey, jonh

**Pull request closed without merging**
